apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dummy-service
spec:
  replicas: 2
  template:
    metadata:
      name: dummy-service
      labels:
        app: dummy-service
    spec:
      containers:
        - name: sensu-agent
          image: gcr.io/engineering-182923/sensu-go
          command: ["/opt/sensu/bin/sensu-agent", "start"]
          env:
            - name: SENSU_BACKEND_URL
              value: ws://sensu-backend.default.svc.cluster.local:8081
            - name: SENSU_SUBSCRIPTIONS
              value: dummy
        - name: dummy-service
          image: gcr.io/engineering-182923/dummy
