apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sensu-backend
spec:
  replicas: 1
  template:
    metadata:
      name: sensu-backend
      labels:
        app: sensu
    spec:
      containers:
        - name: sensu-backend
          image: gcr.io/engineering-182923/sensu-go
          command: ["/opt/sensu/bin/sensu-backend", "start"]
          ports:
            - protocol: TCP
              containerPort: 8080
            - protocol: TCP
              containerPort: 8081
            - protocol: TCP
              containerPort: 3000
